version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devcontainer_jupyter_aginor
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
